networks:
  pa_network:
    external: true

services:
  pa_website:
    container_name: pa_website
    build:
      context: ./PA2
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - pa_api
    networks:
      - pa_network

  pa_api:
    container_name: pa_api
    build:
      context: ./apiBack
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - pa_db
    networks:
      - pa_network

  pa_db:
    container_name: pa_db
    build:
      context: ./bdd
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: apiback
      MYSQL_ROOT_PASSWORD: exemplepwd
    volumes:
      - ./pa_storage:/var/lib/mysql
    networks:
      - pa_network
